name: 'Setup proto and moon toolchains'
author: 'Miles Johnson'
description: 'Installs proto and moon globally when required, and caches the toolchain.'
inputs:
  auto-install:
    default: 'false'
    description: 'Auto-install tools on setup.'
  cache:
    description: 'Toggle caching of the toolchain directory.'
    default: 'true'
  cache-base:
    description:
      'Base branch/ref to save a warmup cache on. Other branches/refs will restore from this base.'
  cache-version:
    description: 'Version of the cache. Can be used to invalidate keys.'
  moon-version:
    default: ''
    description: 'Version of moon to install.'
    required: false
  proto-version:
    default: ''
    description: 'Version of proto to install.'
    required: false
  workspace-root:
    default: ''
    description: 'Path to the moon workspace root (if in a sub-directory).'
    required: false
outputs:
  cache-key:
    description: 'The cache key used for the toolchain folder (~/.proto).'
  cache-hit:
    description: 'A boolean to indicate an exact match was found for the cache key.'
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/post/index.js'
branding:
  icon: 'battery-charging'
  color: 'purple'
